env:
  STACK: java
  BUILD_TECH: java_ant
#   MVN_ARGS: clean install --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: false
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

on:
  push:
  # and the target with some regex to match specific  branch namess
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'
  pull_request:
    branches:
      - master
      - 'FEATURE-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'

jobs:
  Build:
    runs-on: ubuntu-latest 
    
    steps:
    ######## Checkout code ########
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
          
      ######## Setup JDK 11 ########
      - name: set up JDK 11
        id: setup_jdk
        if: ${{ env.STACK == 'java' }}
        uses: actions/setup-java@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          java-version: '11'
          distribution: 'adopt'
              
       
      ######## Build - ANT ########       
      - name: Download sonar scanner jar
        run: wget 'https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar' -O '/home/runner/work/simple-java-maven-app/simple-java-maven-app/lib/junit-4.12.jar'
      
      - name: Build with Ant
        if: ${{ env.BUILD_TECH == 'java_ant'  }}
        run: ant -noinput -buildfile build.xml
      - run: ls -R
      - name: Install Wget
        run: sudo apt install wget
      - name: Download sonar scanner jar
        run: wget 'https://binaries.sonarsource.com/Distribution/sonarqube-ant-task/sonarqube-ant-task-2.7.1.1951.jar' -O '/home/runner/work/simple-java-maven-app/simple-java-maven-app/lib/sonarqube-ant-task-2.7.1.1951.jar'
      - name: Download jacoco jar
        run: |
          wget https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.1/jacoco-0.8.1.zip -O '/home/runner/work/simple-java-maven-app/simple-java-maven-app/lib/jacoco-0.8.1.zip'
          unzip /home/runner/work/simple-java-maven-app/simple-java-maven-app/lib/jacoco-0.8.1.zip
          ls -ltr
           
#wget 'https://search.maven.org/remotecontent?filepath=org/jacoco/org.jacoco.ant/0.8.7/org.jacoco.ant-0.8.7.jar' -O '/home/runner/work/java-junit-template-project/java-junit-template-project/lib/org.jacoco.ant-0.8.7.jar'

#       - name: 'Upload Artifact'
#         uses: actions/upload-artifact@v2.2.3
#         with:
#             name: Jars
#             path: /home/runner/work/java-junit-template-project/java-junit-template-project/lib/org.jacoco.ant-0.8.7.jar!/org/jacoco/ant/antlib.xml

      - name: Sonar
        run: ant sonar -Dsonar.login=d33153c2a482d748cd4db79151f9677dd37f62b0
        
      - name: files
        run: ls -ltrR


      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./*test*.xml  
          
      - name: 'Publish Test results'
        uses: actions/upload-artifact@v2.2.3
        with:
            name: Test Report
            path: ./*.xml
#
#       - name: Generate JaCoCo Badge
#         uses: cicirello/jacoco-badge-generator@v2
#         with:          
#           jacoco-csv-file: target/site/jacoco/jacoco.csv
#           badges-directory: .github/JaCoCo
#           generate-coverage-badge: true
#           coverage-badge-filename: jacoco.svg
#           generate-branches-badge: false
#           branches-badge-filename: branches.svg
#           colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
#           intervals: 100 90 80 70 60 0
#           on-missing-report: fail
#           fail-if-coverage-less-than: 0
#           fail-if-branches-less-than: 0
#           fail-on-coverage-decrease: false
#           fail-on-branches-decrease: false
#       - name: Log coverage percentage
#         run: |
#           echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
#           echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"     
#       - name: Upload JaCoCo coverage report
#         uses: actions/upload-artifact@v2
#         with:
#           name: jacoco-report
#           path: target/site/jacoco/
 
#       - name: SonarQube Scan
#         run: mvn -B sonar:sonar -Dsonar.host.url=http://18.223.255.187:9000/ -Dsonar.login=860a420eb9a5bf5a4f90668f83809ca977fddd88
#       - uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.JavaMavenApp }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

 
